spring:
  datasource:

    url: jdbc:mariadb://10.10.121.150:3306/user

    username: root
    password: P@ssw0rd
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect

