apiVersion: v1
kind: Service
metadata:
  name: mariadb-service
spec:
  selector:
    app: mariadb
  ports:
    - protocol: TCP
      port: {{ .Values.mariadb.port }}
      targetPort: {{ .Values.mariadb.port }}
  clusterIP: None

