apiVersion: v1
kind: Service
metadata:
  name: springboot-service
spec:
  selector:
    app: springboot-app
  ports:
    - protocol: TCP
      port: {{ .Values.springboot.port }}
      targetPort: {{ .Values.springboot.port }}
  type: NodePort

